export const config = {
  APIEndpoint: process.env.REACT_APP_FIREBASE_API_ENDPOINT,
  APIKey: process.env.REACT_APP_FIREBASE_API_KEY,
  AuthDomain: process.env.REACT_APP_FIREBASE_API_AUTHDOMAIN,
  storageBucket: process.env.REACT_APP_FIREBASE_API_STORAGEBUCKET,
  ProjectId: process.env.REACT_APP_FIREBASE_API_PROJECTID,
  StorageBucket: process.env.REACT_APP_FIREBASE_API_ENDPOINT,
  MessagingSenderId: process.env.REACT_APP_FIREBASE_API_MESSAGINGSENDERID,
  AppId: process.env.REACT_APP_FIREBASE_API_APPID,
  MeasurementId: process.env.REACT_APP_FIREBASE_API_MEASUREMENTID,
  API_URL: process.env.REACT_APP_API_ENDPOINT,
  ORG_ID: process.env.REACT_APP_ORG_ID,
  ORG_COLLECTION: process.env.REACT_APP_ORG_COLLECTION,
  QUEST_ORDER_COLLECTION: process.env.REACT_APP_QUEST_ORDER_COLLECTION,
  USER_COLLECTION: process.env.REACT_APP_USER_COLLECTION,
  ORG_QUEST_COLLECTION: process.env.REACT_APP_ORG_QUEST_COLLECTION,
  QUEST_ORDER_ACTION_COLLECTION:
    process.env.REACT_APP_QUEST_ORDER_ACTION_COLLECTION,
  AUTH_ENDPOINT: process.env.REACT_APP_AUTH_ENDPOINT,

  // images
  FIRESTORE_IMAGE_URL: process.env.REACT_APP_WEB_APP_SVG_IMAGE_URL,
  ONBOARD_SVG: process.env.REACT_APP_WEB_APP_SVG_ONBOARD_SVG,
  ONBOARD_BG_SVG: process.env.REACT_APP_WEB_APP_SVG_ONBOARD_BG_SVG,
  GETSTARTED_SVG_2: process.env.REACT_APP_WEB_APP_SVG_GETSTARTED_SVG_2,
  GETSTARTED_SVG: process.env.REACT_APP_WEB_APP_SVG_GETSTARTED_SVG,
  SIGNUP_STICKER_SVG: process.env.REACT_APP_WEB_APP_SVG_SIGNUP_STICKER_SVG,
  MOB_SIGNUP_STICKER: process.env.REACT_APP_WEB_APP_SVG_MOB_SIGNUP_STICKER,
  INVITE_CODE_MOB_STICKER: process.env.REACT_APP_WEB_APP_SVG_MOB_SIGNUP_STICKER,
  INVITE_CODE_STICKER:
    process.env.REACT_APP_WEB_APP_SVG_CREATE_USERNAME_STICKER,
  CREATE_USERNAME_MOB_STICKER:
    process.env.REACT_APP_WEB_APP_SVG_CREATE_USERNAME_MOB_STICKER,
  INVITE_CODE_SIDE_STICKER:
    process.env.REACT_APP_WEB_APP_SVG_INVITE_CODE_MOB_STICKER,
};
